### ISSUE TITLE
cannot run "quick_test.py"

### ISSUE THREAD

**Issue by DAKSHSEMWAL** [jsalbert/music-genre-classification#2]
while running quicktest.py
Using TensorFlow backend.

Traceback (most recent call last):
  File "I:\Coding\Music-Genre-Classification-with-Deep-Learning-master\quick_test.py", line 1, in <module>
    from keras import backend as K
  File "C:\Python27\lib\site-packages\keras\__init__.py", line 2, in <module>
    from . import backend
  File "C:\Python27\lib\site-packages\keras\backend\__init__.py", line 64, in <module>
    from .tensorflow_backend import *
  File "C:\Python27\lib\site-packages\keras\backend\tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
but tensorflow does not support python2.7.14

**Comment by jsalbert** [comment]
Hello, it seems that you don't have tensorflow installed. 
If you read the pre-requisites you will see how to create an environment and install there the project library dependencies. 
```
# Create environment
 virtualenv env_song
 # Activate environment
 source env_song/bin/activate
 # Install dependencies
 pip install -r requirements.txt
```
Also this project is a bit old now and it was made with Keras version 1, running over Theano, not Tensorflow. In `requirements.txt` you can see the specific version that was used. Not sure if it will run with the newest versions. 
[Here](https://keras.io/backend/) it is shown how to change the backend that Keras is using.

**Comment by pandey1996** [comment]
try sudo pip install --upgrade tensorflow worked for me at that part having issues later though

**Comment by Seedak** [comment]
Hi,
I am trying to run quick_test.py with theano as backend for keras and i am getting this error
Please Help

Traceback (most recent call last):
  File "C:/Users/t****/PycharmProjects/Music-Genre-Classification-with-Deep-Learning-master/quick_test.py", line 47, in <module>
    X_test, num_frames_test = extract_melgrams(test_songs_list, MULTIFRAMES, process_all_song=False, num_songs_genre='')
  File "C:\Users\t****\PycharmProjects\Music-Genre-Classification-with-Deep-Learning-master\utils.py", line 111, in extract_melgrams
    melgram = ap.compute_melgram_multiframe(song_path, process_all_song)
  File "C:\Users\t****\PycharmProjects\Music-Genre-Classification-with-Deep-Learning-master\audio_processor.py", line 99, in compute_melgram_multiframe
    n_fft=N_FFT, n_mels=N_MELS) ** 2,
  File "C:\Users\t****\venv\lib\site-packages\librosa\feature\spectral.py", line 1371, in melspectrogram
    mel_basis = filters.mel(sr, n_fft, **kwargs)
  File "C:\Users\t****\venv\lib\site-packages\librosa\filters.py", line 238, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,257) (0,)

**Comment by leon0514** [comment]
> Hi,
> I am trying to run quick_test.py with theano as backend for keras and i am getting this error
> Please Help
> 
> Traceback (most recent call last):
> File "C:/Users/t****/PycharmProjects/Music-Genre-Classification-with-Deep-Learning-master/quick_test.py", line 47, in
> X_test, num_frames_test = extract_melgrams(test_songs_list, MULTIFRAMES, process_all_song=False, num_songs_genre='')
> File "C:\Users\t****\PycharmProjects\Music-Genre-Classification-with-Deep-Learning-master\utils.py", line 111, in extract_melgrams
> melgram = ap.compute_melgram_multiframe(song_path, process_all_song)
> File "C:\Users\t****\PycharmProjects\Music-Genre-Classification-with-Deep-Learning-master\audio_processor.py", line 99, in compute_melgram_multiframe
> n_fft=N_FFT, n_mels=N_MELS) ** 2,
> File "C:\Users\t****\venv\lib\site-packages\librosa\feature\spectral.py", line 1371, in melspectrogram
> mel_basis = filters.mel(sr, n_fft, **kwargs) File "C:\Users\t****\venv\lib\site-packages\librosa\filters.py", line 238, in mel
> lower = -ramps[i] / fdiff[i]
> ValueError: operands could not be broadcast together with shapes (1,257) (0,)

I got the same error,do you have any solution for this problem?
