### ISSUE TITLE
audio_processor.py : ValueError: operands could not be broadcast together with shapes (1,257) (0,) 

### ISSUE THREAD

**Issue by tharindu326** [jsalbert/music-genre-classification#9]
Hi, I'm trying to work on your codes but have a problem.
The problem I'm having is the value error. ValueError: operands could not be broadcast together with shapes (1,257) (0,) 
It looks like dimension problem but can't solve it.

**Error**

Traceback (most recent call last):
  File "G:/Music-Genre-Classification-with-Deep-Learning-master/quick_test.py", line 49, in <module>
    X_test, num_frames_test= extract_melgrams(test_songs_list, MULTIFRAMES, process_all_song=False, num_songs_genre='')
  File "G:\Music-Genre-Classification-with-Deep-Learning-master\utils.py", line 111, in extract_melgrams
    melgram = ap.compute_melgram_multiframe(song_path, process_all_song)
  File "G:\Music-Genre-Classification-with-Deep-Learning-master\audio_processor.py", line 99, in compute_melgram_multiframe
    n_fft=N_FFT, n_mels=N_MELS)**2,
  File "C:\Program Files\Python37\lib\site-packages\librosa\feature\spectral.py", line 1371, in melspectrogram
    mel_basis = filters.mel(sr, n_fft, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\librosa\filters.py", line 238, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,257) (0,) 

Plz can anyone help me with this!!!

**Comment by tharindu326** [comment]
It is an issue with compatibility of librosa 0.5 with other plugins (if you are not using required versions of plugins)
I solved it by update it to 0.6 version and change the librosa.logamplitude to librosa.core.amplitude_to_db .
This worked for me!!
